### ISSUE TITLE
Extravagant permission requirements on storage account

### ISSUE THREAD

**Issue by Timovzl** [hashicorp/azure-pipelines-extension-terraform#16]
The extension, at least when performing `terraform init`, performs certain operations that it shouldn't need to, requiring quite a lot of permissions on not just the container, but even the whole storage account.

The problematic operation I'm running into is `listKeys` _on the whole storage account_. This should not be necessary. We have specified the subscription or (as in my case) service connection, the resource group, the storage account, the container, and the blob key (i.e. name). The extension knows _exactly_ what to look for. Listing anything should be unnecessary.

The error message is this (line breaks mine):

```
Failed to get existing workspaces: Error retrieving keys for Storage Account "___":
storage.AccountsClient#ListKeys: Failure responding to request:
StatusCode=403 -- Original Error: autorest/azure: Service returned an error.
Status=403 Code="AuthorizationFailed" Message=
"The client '___' with object id '___' does not have authorization to perform action
'Microsoft.Storage/storageAccounts/listKeys/action' over scope
'/subscriptions/___/resourceGroups/___/providers/Microsoft.Storage/storageAccounts/___' or the scope is invalid.
If access was recently granted, please refresh your credentials."
```

My best guess is that the containers are listed in order to check if the required container exists. I expect that this could instead be achieved by simply accessing the container and handling a response saying it does not exist.

I haven't gotten past this error, but it seems likely that the extension will next perform `listKeys` _on the container itself_. This could present the same problem (even though the scope is less extravagant).

Why is this so problematic, you ask - apart from requiring more permissions than strictly necessary?

As we know, Terraform stores sensitive data in the `tfstate` file. For example, we might pull the database administrator password out of Azure KeyVault (or even generate it on the spot with `random_password`) and create a database resource with that password. Now the password is not just in our well-protected KeyVault, but also in the `tfstate` file in the storage account. This makes it essential to use a well-protected storage account - for example, one that is only accessible to the service connection (through a dedicated app registration).

Such a dedicated storage account tends to live in a different resource group, since the main resource group usually grants team members access to its resources, which we want to avoid. In our case, a storage account managed by administrators does not allow listing all the keys in a container, let alone listing all the containers in the storage account (i.e. other teams' Terraform storage containers)!

Could the extension be improved such that it only performs the operations it strictly needs to?

**Comment by Timovzl** [comment]
Did I post this in the correct repository?

**Comment by charleszipp** [comment]
@Timovzl did you mean to post in one of these? 

I dont believe this one is published to the marketplace

https://github.com/microsoft/azure-pipelines-extensions (MSFT DevLabs)
https://github.com/charleszipp/azure-pipelines-tasks-terraform
