### ISSUE TITLE
Can't find in marketplace / link to marketplace?

### ISSUE THREAD

**Issue by bneijt** [hashicorp/azure-pipelines-extension-terraform#8]
The documentation states it should be in the marketplace, but I can't find it.

Could you add a link to the documentation stating where in the marketplace this can be found?

**Comment by MichaelMcCoyTech** [comment]
Same problem.  Can you give a link to this extension in the marketplace ??

**Comment by bneijt** [comment]
Currently our team uses a Microsoft extension found at https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

**Comment by heoelri** [comment]
I've the same question. There's a whole bunch of Terraform extensions in the Marketplace but it's not fully clear which one we're talking about here.

**Comment by heoelri** [comment]
@jlorich can you help us here?

**Comment by charleszipp** [comment]
I think the short answer is its not published. Willing to merge mine into this one if it helps. See #9

**Comment by dewolfs** [comment]
I just viewed the MS Ignite session about Terraform and Azure DevOps from @jlorich. When will this extension become available in the marketplace?

**Comment by sean-kang** [comment]
Is this repo abandoned?

**Comment by bneijt** [comment]
Guess so, see https://github.com/hashicorp/azure-pipelines-extension-terraform/issues/36
